### ISSUE TITLE
[BUG] cannot continue after taking photo

### ISSUE THREAD

**Issue by xxyxxyxyx1** [Akylas/OSS-DocumentScanner#163]
### Version

F-Droid IzzyOnDroid 1.4.15.56

### What platform are you using?

Android

### OS Version

Pixel 8 Pro, android 14, march 5 2024 update

### What happened?

After a photo is taken (in manual or automatic mode), there is a popup that says:
```Cannot read properties of null (reading 'unshift')```

The only option to close the popup is `OK`. When I tap the checkmark to continue, the popup happens again. I cannot proceed. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@xxyxxyxyx1 sorry for the latest answer. Can you tell me if this is still happening with latest version? Any chance to get a logcat once the error happens?
Thanks

**Comment by farfromrefug** [comment]
@xxyxxyxyx1 ok so just run the app, reproduce the issue. Then use `adb logcat` to get the current logcat. content.
You can call `adb logcat -c` to clear the logcat before reproducing the issue.
Then share the content returned by `adb logcat`
Thanks

**Comment by xxyxxyxyx1** [comment]
It is attached 
[logcat.txt](https://github.com/Akylas/OSS-DocumentScanner/files/14839211/logcat.txt)

**Comment by farfromrefug** [comment]
@xxyxxyxyx1 sadly i dont see anything in the log. Could you try this build https://github.com/Akylas/OSS-DocumentScanner/releases/tag/test_android? I should even receive a bug report directly

**Comment by xxyxxyxyx1** [comment]
done

**Comment by farfromrefug** [comment]
@xxyxxyxyx1 did you restart the app after the crash? (to ensure the log is sent)

**Comment by xxyxxyxyx1** [comment]
I have caused the bug more than once. 
The app does not actually crash when the bug happens. After I press "OK" on the error popup, I can continue using the app. I just cannot continue in the scanning process.

**Comment by farfromrefug** [comment]
@xxyxxyxyx1 ok got the error!  But to me here the erorr is `Cannot read properties of null (reading 'length')` is that what you see?

**Comment by farfromrefug** [comment]
@xxyxxyxyx1 ok so i made a fix where it should not give an error for you anymore. Though there is still something wrong.
Could you test that build again that i updated https://github.com/Akylas/OSS-DocumentScanner/releases/tag/test_android ? You should not see an error but i should still get a report with more details allowing to understand why it fails for you

**Comment by xxyxxyxyx1** [comment]
It seems to work now with the new version. I am able to take a photo and export a PDF. 

I have not observed an error including the text "(reading 'length')" 

In brief testing, I found two other problems, but they seem unrelated: 
- in 2 out of 3 papers (A4 two-column text-only documents), the app chose only 1 paragraph on the page, instead of the whole page. The blue preview rectangle looked approximately correct when I took the pictures. 
- after exporting a PDF, a filename is displayed with an "open" popup. The displayed filename is wrong, starting with "primary%3A", and clicking "open" results in a file-not-found in the pdf viewer. However, the PDF is saved correctly: I can find the PDF in a file browser with the correct filename in the correct location.

**Comment by farfromrefug** [comment]
@xxyxxyxyx1 it does not fail for you anymore but the issue is still there. But i got the correct bug report from you now and i can investigate it ! thanks a lot.

Could you open new issues for the other 2 with more details? I dont understand what you mean by `he app chose only 1 paragraph on the page` . are you talking about OCR? Please explain in details with screenshots if relevant.
And the second one maybe a screenshot of the dialog with the wrong text could help.
Thanks

**Comment by catfluoride** [comment]
Just a +1, as the same is happening for me; test_android version works fine.

**Comment by farfromrefug** [comment]
@catfluoride are you seeing an error message? if so what is it? Or does it simply crash?

**Comment by catfluoride** [comment]
> @catfluoride are you seeing an error message? if so what is it? Or does it simply crash?

Hi! I got an error message similar to that of OP: `Cannot read properties of null ("reading 'image')`

**Comment by farfromrefug** [comment]
@catfluoride ok this one is a regression in latest release. I am on it. Sorry!

**Comment by catfluoride** [comment]
> @catfluoride ok this one is a regression in latest release. I am on it. Sorry!

No need to apologize, man. You created a wonderful app. Thank you for your hard work!

**Comment by farfromrefug** [comment]
@catfluoride should be fixed in new release (only on github for now)

**Comment by catfluoride** [comment]
> @catfluoride should be fixed in new release (only on github for now)

Indeed. It works perfectly now. Thanks a lot! <img class="emoji" alt="heart" height="20" width="20" src="https://github.githubassets.com/assets/2764-982dc91ea48a.png">
