### ISSUE TITLE
[BUG] On scanning screen, when the display is in landscape orientation, all elements except the zoom slider and the close button are non‑functional.

### ISSUE THREAD

**Issue by TranslucentFoxHuman** [Akylas/OSS-DocumentScanner#509]
### Which app is your issue for

Document Scanner

### Version

1.16.1 Build 124

### What platform are you using?

Android

### OS Version

Android 8.1, 14 and 15

### What happened?

On scanning screen, when the display is in landscape orientation, all elements except the zoom slider and the close button are non‑functional. 
  
When the screen is in portrait mode, everything works normally. However, when the screen is rotated to landscape, all elements except the zoom slider and the close button stop functioning. Pressing the flash button or the light button toggles the Batch Mode button on or off.

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by OpensourceGhost** [comment]
Same Issue however using ios 18.7.0 and occurs with both portrait and landscape modes. 

 Issue is  screen gets stuck on capture and overall app has been glitching for past 2 updates no longer shows green outline for auto scan future and requires pressing green button for capturing prior to latest update, however now does not function at all and does not scan or export documents. Thanks a ton, would donations help appreciate the app.

**Comment by farfromrefug** [comment]
@TranslucentFoxHuman @OpensourceGhost sorry about the trouble. I will fix it tomorrow.
For now you can use it in portrait as all dhoulf be good in portrait. 
The issue started when i tried to enforce portrait

**Comment by TranslucentFoxHuman** [comment]
I’ve confirmed that the fix has been applied. It’s working perfectly. Thank you for making the changes, and thank you for the great software!

**Comment by OpensourceGhost** [comment]
Is the issue still being fixed it hasn't been resolved for IOS after updating software issue still persist app stuck on capture screen and no auto detection working.

**Comment by farfromrefug** [comment]
@OpensourceGhost i dont think you are talking about the same issue?  This is about landscape

**Comment by OpensourceGhost** [comment]
The issue of freezing on capturing occurs in landscape mode also as well as portrait mode all functions are not working and the close x button does not work have to quit entire app to go back to start page.

**Comment by TranslucentFoxHuman** [comment]
@OpensourceGhost That problem is probably unrelated to this issue. In the issue I opened, it worked fine when I rotated the screen back to portrait. It would probably be better to open a new issue.

**Comment by OpensourceGhost** [comment]
> [@OpensourceGhost](https://github.com/OpensourceGhost) That problem is probably unrelated to this issue. In the issue I opened, it worked fine when I rotated the screen back to portrait. It would probably be better to open a new issue.

Just Checked issue seems to be resolved since writing last message, all functions are normal thank you !

**Comment by farfromrefug** [comment]
@OpensourceGhost you mean your issue is fixed ?

**Comment by OpensourceGhost** [comment]
> [@OpensourceGhost](https://github.com/OpensourceGhost) you mean your issue is fixed ?

Well it was working briefly  I uploaded photos from phone gallery , and afterwards it was able capture images but without auto-scan feature and allowed me to crop documents by manually adjusting green border. However now it is back to same issue and still not working and this time even crashed , but as of now still same issue as described above. Not sure the issue or how to report or log any bugs from app in itself and not showing any error codes. Just stuck on capturing and freezes and have to quit app. If issue is persistent don't mind just uploading using selected limited access photos thanks for the app.

**Comment by farfromrefug** [comment]
@OpensourceGhost could you open an issue and explain your issue in details. 
i have fixed a lot of issues today and will make a new release. BTW don't forget to say if your are on android or iOS and the is version
